# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
 username

ko_fi: nvsenpai # Replace with a single Ko-fi username
tidelift: ariasuxyz/xyzapi
community_bridge: # Replace with a single Community Bridge project-name e.g. cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry

